CREATE SCHEMA PizzaStoreSchema

GO

SELECT * FROM Users;

-- DROP TABLE Users
CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	FirstName NVARCHAR(128) NOT NULL,
	LastName NVARCHAR(128) NOT NULL,
	DefaultLocation INT FOREIGN KEY REFERENCES Locations(Id) NOT NULL
);

-- DROP TABLE Locations
CREATE TABLE Locations
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Pepperoni INT NOT NULL,
	Chicken INT NOT NULL,
	Ham INT NOT NULL,
	Sausage INT NOT NULL,
	Mushroom INT NOT NULL,
	Onion INT NOT NULL,
	Pineapple INT NOT NULL,
	Jalapeno INT NOT NULL,
	Olive INT NOT NULL,
	Tomato INT NOT NULL
);


-- DROP TABLE Orders
CREATE TABLE Orders
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	OrderTime Datetime NOT NULL,
	LocationID INT FOREIGN KEY REFERENCES Locations(Id) NOT NULL,
	Price Money NOT NULL
);

-- DROP TABLE Pizzas
CREATE TABLE Pizzas
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	OrderId INT FOREIGN KEY REFERENCES Orders(Id) NOT NULL,
	PizzaSize NVARCHAR(128) NOT NULL,
	Pepperoni BIT NOT NULL,
	Chicken BIT NOT NULL,
	Ham BIT NOT NULL,
	Sausage BIT NOT NULL,
	Mushroom BIT NOT NULL,
	Onion BIT NOT NULL,
	Pineapple BIT NOT NULL,
	Jalapeno BIT NOT NULL,
	Olive BIT NOT NULL,
	Tomato BIT NOT NULL
);